#!/usr/bin/env python3
# =================================================================
# vectorize -- OpenCL kernel vectorize compiler
#
# This is the main program for the kernel vectorization compiler,
# which just parses command-line options, figures out which source
# files to read and write to, and invokes the different stages
# of the compiler properly.
#
# Copyright (C) 2016, Marcio Machado Pereira
# License: BSD
# =================================================================

import os
import sys
sys.path.append(os.environ['LLVM_INCLUDE_PATH'] + '/vectorize')

from vc_parser import vcParser, ParseError
from vc_transform import VcTransform, TransformError
from vc_code import vcCode


class Compiler:
    """ This object encapsulates the compiler and serves as a
        facade interface to the 'meat' of the compiler underneath.
    """

    class CompileError(Exception):
        """ Exception raised when there's been a compilation error. """
        pass

    def __init__(self):
        self.total_errors = 0
        self.total_warnings = 0

    def _parse(self, ast_file, debuglevel):
        """ Parses the source code. If ast_file != None,
            prints out the abstract syntax tree.
        """
        self.parser = vcParser()
        self.ast = self.parser.parse(self.code, '', debuglevel)
        if ast_file:
            self.ast.show(buf=ast_file, showcoord=True)

    def _transform(self, asm_file, out_file):
        """ Generate the OpenCl kernel from AST with vector statements. """
        self.transform = VcTransform()
        self.transform.visit(self.ast)
        if asm_file:
            self.ast.show(buf=asm_file, showcoord=True)
        self.code = vcCode()
        if out_file:
            __clcode = self.code.visit(self.ast)
            out_file.write(__clcode)

    def _do_compile(self, out_file, ast_file, asm_file, debuglevel):
        """ Compiles the code to the given file object. """
        self._parse(ast_file, debuglevel)
        self._transform(asm_file, out_file)

    def _print_stats(self, silent):
        """ Prints the total number of errors/warnings from compilation. """
        if not silent:
            print("<vectorize> %d errors, %d warnings." % (self.total_errors, self.total_warnings))

    def compile(self, code, outfile, astfile, asmfile, silent, debuglevel):
        """ Compiles the given code string to the given file object. """
        self.code = code
        try:
            self._do_compile(outfile, astfile, asmfile, debuglevel)
        except ParseError:
            self.total_errors += 1
            if not silent:
                print(",vectorize> Errors encountered.")
            return False
        except (Compiler.CompileError, TransformError):
            self.total_errors += 1
            self._print_stats(silent)
            if not silent:
                print("<vectorize> Errors encountered.")
            return False
        self._print_stats(silent)
        if not silent:
            print("<vectorize> Compile successful.")
        return True


def run_compiler():
    """ Runs the command-line of vectorize compiler. """
    if len(sys.argv) < 2:
        print("Usage: ./vectorize <source-file> [-silent] [-ast] [-asm] [-debug]")
        sys.exit(1)
    show_ast = False
    show_asm = False
    silent = False
    debuglevel = 0
    params = sys.argv[1:]
    files = sys.argv[1:]
    for param in params:
        if param[0] == '-':
            if param == '-ast':
                show_ast = True
            elif param == '-asm':
                show_asm = True
            elif param == '-silent':
                silent = True
            elif param == '-debug':
                debuglevel = 2
            else:
                print("<vectorize> Unknown option: %s" % param)
                sys.exit(1)
            files.remove(param)

    for file in files:
        if file[-3:] == '.cl':
            out_filename = file
        else:
            out_filename = file + '.cl'
        source_filename = out_filename[:-3] + '.tmp'
        os.rename(out_filename, source_filename)
        source = open(source_filename, 'r')
        code = source.read()
        source.close()

        open_files = []
        ast_file = None
        if show_ast:
            ast_filename = out_filename[:-3] + '.ast'
            print("Outputting the Abstract Syntax Tree to %s." % ast_filename)
            ast_file = open(ast_filename, 'w')
            open_files.append(ast_file)
        asm_file = None
        if show_asm:
            asm_filename = out_filename[:-3] + '.asm'
            print("Outputting the Transformed AST to %s." % asm_filename)
            asm_file = open(asm_filename, 'w')
            open_files.append(asm_file)

        out_file = open(out_filename, 'w')
        open_files.append(out_file)
        retval = Compiler().compile(code, out_file, ast_file, asm_file, silent, debuglevel)
        for f in open_files:
            f.close()
        if retval:
            sys.exit(retval)
        else:
            if not silent:
                print("Was not possible to vectorize the kernel file!")
            os.rename(source_filename, out_filename)
    sys.exit(retval)

if __name__ == '__main__':
    run_compiler()
